///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __SIPPTUTA0MODEL_H__
#define __SIPPTUTA0MODEL_H__

#include <sipp.h>
#include <sippTestCommon.h>



//The full-frame buffers
extern UInt8      DDR_DATA SippTutA0Model_dmaIn0_buffer[512      * 512     * 1  ]ALIGNED(8);
extern UInt8      DDR_DATA SippTutA0Model_dmaOut0_buffer[512      * 512     * 1  ]ALIGNED(8);
	
///

typedef struct SippTutA0Model
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *dmaOut0;

} SippTutA0Model;

void readSippTutA0ModelInput(SippTutA0Model *pPl);
void writeSippTutA0ModelOutput(SippTutA0Model *pPl);

void buildSippTutA0Model(SippTutA0Model *pPl);
void configSippTutA0Model(SippTutA0Model *pPl);


#endif