# ------------------------------ Myriad Project Settings -----------------------------#
# This file is automatically generated by eclipse, do not change it manually
MV_PROJECT_TYPE=Sipp
# End of myriad project settings
# ------------------------------ Myriad Project Settings End -------------------------#